name: Build and run zemu tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:
    branches:
      - develop
      - master
      - dev

jobs:
  build_application:
    name: Build application using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      upload_app_binaries_artifact: "compiled_app_binaries"
      flags: "RELEASE_BUILD=1"

  ragger_tests:
    name: Run ragger tests using the reusable workflow
    needs: build_application
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_ragger_tests.yml@v1
    with:
      download_app_binaries_artifact: "compiled_app_binaries"

  zemu_tests:
    name: Run zemu tests
    needs: build_application
    runs-on: ${{ github.repository_owner == 'zondax' && 'zondax-runners' || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v4
        with:
          name: compiled_app_binaries
          path: build
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl protobuf-compiler build-essential git python3 python3-pip \
            libusb-1.0-0 libudev-dev
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
          sudo update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 10
      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: cd tests_zemu && yarn install
      - name: Run zemu tests
        run: cd tests_zemu && yarn test
