name: Build and run zemu tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:
    branches:
      - develop
      - master
      - dev

jobs:
  build_application:
    name: Build application using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      upload_app_binaries_artifact: "compiled_app_binaries"
      flags: "RELEASE_BUILD=1"

  ragger_tests:
    name: Run ragger tests using the reusable workflow
    needs: build_application
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_ragger_tests.yml@v1
    with:
      download_app_binaries_artifact: "compiled_app_binaries"

  zemu_tests:
    name: Run zemu tests
    needs: build_application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: compiled_app_binaries
          path: build
      - name: Install dependencies
        run: cd tests_zemu && yarn install
      - name: Run zemu tests
        run: cd tests_zemu && yarn test
